### ISSUE TITLE
Enable guest debugging in accelerators

### ISSUE THREAD

**Issue by AlexAltea** [AlexAltea/orbital#10]
All accelerators, except KVM and TCG, lack the possibility of debugging the guest systems. Ideally, this feature should be implemented in the corresponding accelerators:

- [x] _HAXM_: https://github.com/intel/haxm/issues/81
- [x] ~~_WHPX_: (To be reported).~~ (No longer relevant).
- [x] ~~_Xen_: (To be reported).~~ (No longer relevant).

**Comment by JohnHolmesII** [comment]
Is this another thing that's going to wind up as a PR for HAXM, or are you just going to put it on the QEMU side?

I ask since it seems like HAXM is the only accelerator left standing.

**Comment by AlexAltea** [comment]
> Is this another thing that's going to wind up as a PR for HAXM [....] ?

Yes, I'd rather implement it as part of HAXM. Check also the thread at:
https://lists.gnu.org/archive/html/qemu-devel/2018-04/msg00030.html

Additionally, I'm most likely going to work on Linux support on HAXM as well, so we can completely ignore the KVM/Xen/WHPX/HVF backends.

My reasoning to stand by HAXM instead of alternatives is because it's:
- Open-source (unlike HVF, WHPX, and most commercial hypervisors).
- Cross-platform (unlike HVF, WHPX, KVM).
- Permissive license (unlike KVM, Xen).

Even if HAXM is less mature, it deserves to be prioritized.

**Comment by AlexAltea** [comment]
Guest debugging on HAXM is pending reviews, but can already be used with Orbital. Issue closed.
