### ISSUE TITLE
Create container for decrypted blobs

### ISSUE THREAD

**Issue by AlexAltea** [AlexAltea/orbital#19]
Since there's no publicly known method of dumping keys required to decrypt SELF files, we emulate decryption by hashing encrypted blobs sent to SAMU and returning hardcoded decrypted blobs that come from an actual console (these are stored in `bin/crypto/${hash}.bin`).

Unfortunately, there are 36,000+ blobs for the 5.00 system files alone. Adding games/applications could easily bring this figure up to 100,000+ files, which causes unnecessary overhead in the host filesystem.

To solve this we need:
- [x] Choosing a container format to store all blobs in a single file.
- [x] Updating `liverpool_gc_samu_fakedecrypt` to make use of this new container.
- [x] Creating a tool, ideally in Python, to easily add/remove/modify blobs inside the container.

Regarding the first point, I'm open to suggestions. Desired properties of the container are:
- Fast random-access reading times ~(writing times are less relevant)~.
- Dynamic growth/shrinkage to avoid wasting space.
- Compression for individual blobs (optionally).
- Standardized or widely-used format.

**Comment by VelocityRa** [comment]
How about packaging them in a zip, with the compression level set to "store" (ie. no compression)?

**Comment by mirh** [comment]
If you don't care about compression, then .tar is your standard for archives....
And if the things are quite compressible then, there are [plenty](https://sites.google.com/site/powturbo/home/benchmark) of more or less novel compression standards for that

**Comment by AlexAltea** [comment]
@mirh I'd love to use *.tar* files, but their weakness are random-accesses: It needs to traverse the entire archive to locate the desired files: https://en.wikipedia.org/wiki/Tar_(computing)#Random_access
Thanks for pointing out LzTurbo, I'll see how LZ77 compares to ZIP.

@VelocityRa Good point, I hadn't considered *.zip* files, I'll do few benchmarks and see if it's suitable. Probably, it won't be the best container since it was never meant to be a "database" with plenty of random-accesses but it should be better than *.tar*, plus it allows for compression.

**Comment by jfhs** [comment]
I think it depends on what is the goal here. If it's to get as fast as possible, I would think of format like that:
1. FILE DATA
2. Binary search tree (BST) with hashes as keys and ptr + length as data. Can be serialized as an array of structs:
   * File hash (key)
   * Left child index OR 0 if none
   * Right child index OR 0 if none
   * Offset to file data in container
   * Length of data
3. Offset of BST (absolute or from EOF)
4. EOF

Search should be log(n) (~15 lookups into BST for 30k files).
Adding files will require only to append to `FILE DATA` and either insert into BST (but that might make it unbalanced) or completely rebuild it to keep reading as fast as possible.
Removal isn't great, will need to "defragment" file to avoid holes, but it doesn't seem like removal will be needed at all.

If best speed isn't needed, I think zip should suffice. It won't need any special tools to manipulate file and there are plenty of good libs to read from zip on qemu side.
Only downside is linear lookup and some space for zip features (timestamps, attributes etc.)
Given that today `liverpool_gc_samu_fakedecrypt` hashes whole input buffer to get filename, I would question if reading from zip vs custom format would make much of a difference.

**Comment by mirh** [comment]
> I'd love to use .tar files, but their weakness are random-accesses

Oh, right. In that case I know [.xz](https://tukaani.org/xz/format.html) is very very strong with random access. 
Not sure instead how algorithms based on ANS behaves there.

**Comment by JohnHolmesII** [comment]
@jfhs wouldnt a simple hashmap be a better idea? Why waste time constantly rebalancing a tree?

**Comment by JohnHolmesII** [comment]
@jfhs Don't use a bucketed hash map. Use a flat hashmap like skarupke's.
@AlexAltea This would also definitely minimize read, as its constant.

Consider zips within zips. Have each blob be compressed within an outer "store" mode zip. Use a flathasmap outside of this, where the values are simply offsets in the outer zip.

This accomplishes every goal listed. The only thing is having two files, but I think that's simple enough to manage.

**Comment by AlexAltea** [comment]
Not sure if this is caused by poor ZIP implementations or just shortcoming of the ZIP specification for our particular use-case, but .ZIP files have become too slow: e.g. my system required 10-ish minutes to update our `blobs.zip` file in order to add PUP blobs on top of the existing SELF blobs.

Consequently, I'm reopening the issue, and adding an extra requirement for the next format:
"*Fast write/update times given a static batch of blobs (no need for random-access writes though)*".
In addition of:

> - Fast random-access reading times (~writing times are less relevant~).
> - Dynamic growth/shrinkage to avoid wasting space.
> - Compression for individual blobs (optionally).
> - Standardized or widely-used format.


Related: https://github.com/AlexAltea/orbital-qemu/pull/26

**Comment by jihiggins** [comment]
Would HDF5 work for this? Checks a lot of the boxes (python support, widely used, can use compression, dynamic growth / shrinkage, etc) It's not a perfect fit (would have to store stuff as strings probably), but seems like it'd work better than a large zip. The main problem people run into with it seems to be parallel read / write access, which doesn't seem like an issue for this use case.

Another potential solution is an object storage type deal (maybe something like min.io, which lets you set up an S3 style object store locally and is open source.) 

I think a lot of the ready made solutions for this type of problem are going to be cloud / data science oriented, since those are the most common situations where you end up having a million binary files that need fast random-access performance

**Comment by AlexAltea** [comment]
Blobs are no longer needed.
