### ISSUE TITLE
Configuration files

### ISSUE THREAD

**Issue by AlexAltea** [AlexAltea/orbital#25]
It would be a good idea to centralize all configuration-related settings in one or multiple files.

## Features

The key features that would be desirable from this system are:

* __Standard specification__: Preferably a widespread and standardized format for which serializers/unserializers exist, e.g. XML, JSON, YAML. Nothing custom please! Another desirable feature would be native support for `uint64_t` types (which should disqualify JSON).

* __Multiple configurations__: It should be possible to specify one or multiple configuration files via CLI arguments, e.g. `-c config1.xxx -c config2.xxx [...]`, where the keys specified in the latter configuration files override the keys in the former ones (if any). In the absence of such arguments, like when a user double-clicks the executable/shortcut, it will implicitly default to `config.xxx`. All explicitly or implicitly opened configuration files will be created if missing.

* __Nested configurations__: To prevent excessive verbosity in CLI arguments, it should be possible to specify a `base` key in the configuration file (*A*), containing a path to another configuration file (*B*). The rest of the keys in *A* will override the ones in *B*. Similarly, *B* is allowed to inherit more keys from another base configuration file *C*, and so on. The loader should prevent circular dependencies!

* __GUI configuration editor__: We should provide a settings menu to change (at least some) of the configuration keys in the file. When saving changes: if multiple configuration files have been specified in the CLI arguments, only the last one will be modified. If that file contains nested references to other files, those will be ignored, i.e. only the top level file file will be modified.

If anything else comes to your mind, please feel free to suggest it in this thread.

## Specification

The kind of keys that these configuration files would store are (just a draft!):

- `base`: Path to another configuration file.
- `kernel`: Default kernel to be loaded.
- `sku`: Console SKU.
- `hardware`:
  - `aeolia`:
    - (*TODO*)
  - `belize`:
    - (Similar to *aeolia*. Could be ignored depending on the *sku*)
  - `baikal`:
    - (Similar to *aeolia*. Could be ignored depending on the *sku*)
  - `liverpool`:
    - `gc`:
      - `rom`: PCI Option ROM image.
      - (*TODO*)
    - (*TODO*)
- `patches`:
  - `kernel`:
    - `hash1`:
      - `addr1`: `bytes1`
      - `addr2`: `bytes2`
    - `hash2`:
      - `addr1`: `bytes1`
      - `addr2`: `bytes2`
      - `addr3`: `bytes3`
  - `user`:
    - `hash1`:
      - `addr1`: `bytes1`

Notes:
1. All paths should be absolute or relative to the parent folder of the current file.
2. Hashes are specified via `^([0-9A-Fa-f]{2})+$`, input data and hash function are still to be discussed.
3. Bytes are specified via `^([0-9A-Fa-f]{2})+$`. Spaces are ignored.

---

Contributors are welcome to solve this issue:
* Difficulty: Medium.
* Code: https://github.com/AlexAltea/orbital-qemu/blob/master/vl.c
* Tasks: Debugging, coding.

**Comment by AlexAltea** [comment]
A 500 USD bounty has been allocated for @MasonLeeBack for solving this issue.

**Comment by g--o** [comment]
Is the bounty still allocated?

**Comment by AlexAltea** [comment]
Yeah, but the code will be integrated directly into *orbital-ng*, not *orbital-qemu*.
