### ISSUE TITLE
What's TBD?

### ISSUE THREAD

**Issue by wictorChaves** [AlexAltea/orbital#49]
I was seeing the specs and I had a question, what's TBD?

**Comment by Johnnyboc** [comment]
TBD is an abbreviation often meaning in ordinary writing "to be discussed" "to be done", "to be defined", "to be decided", "to be determined", "to be deleted", “to be denounced”, etc.

Unless it means something else for this project.

**Comment by HolyMcDiver** [comment]
@AlexAltea Unnecessary issue. Please close.

**Comment by AlexAltea** [comment]
@wictorChaves As mentioned by @Johnnyboc, it means "To Be Disclosed".
