### ISSUE TITLE
lack of package openssl-devel causes issues when compiling orbital-qemu

### ISSUE THREAD

**Issue by zecoxao** [AlexAltea/orbital#53]
when compiling orbital-qemu on windows, the package openssl-devel is necessary to build it, otherwise some necessary .c files aren't generated and the compilation fails.

The compilation will end here without the package:
ui/input-keymap.c:8:10: fatal error: ui/input-keymap-atset1-to-qcode.c: No such file or directory
 #include "ui/input-keymap-atset1-to-qcode.c"
And will compile successfully with it

**Comment by MasonLeeBack** [comment]
PR #55 includes this as a build step. Sometimes pacman/msys2 doesn't install this by default.

**Comment by AlexAltea** [comment]
Since the PR solves an actual problem, I've decided to merge it right away. However, I won't close this issue yet, because it's not clear to me why would `ui/input-keymap*` files require `openssl-devel` at all.

@zecoxao Could you please debug why is that happening?

**Comment by zecoxao** [comment]
sure, let me check where i found the answer for this

**Comment by zecoxao** [comment]
it was here https://stackoverflow.com/questions/41798118/errorrootcode-for-hash-md5-was-not-found (third answer, the error is the same)

**Comment by AlexAltea** [comment]
Thank you, that makes sense. So it's due to `orbital-qemu/ui/keycodemapdb/tools/keymap-gen` trying to `import hashlib`, which in turn requires those *openssl* headers.

In that case, I consider that @MasonLeeBack's patch at #55 solves this issue.
