### ISSUE TITLE
link to download to test in win 10 where would it have?

### ISSUE THREAD

**Issue by manotroll** [AlexAltea/orbital#58]
link to download to test in win 10 where would it have?

**Comment by telans** [comment]
`This project is not ready for end users. No binaries are provided, so you must build each of the three components (BIOS, GRUB, QEMU) yourself. Furthermore, configuring the emulator to do something will be hard, as you will need to dump and decrypt the entire PS4 filesystem and sflash, including the kernel. You might find hints on how to do this in the few scattered .sh files in this repo. Of course, in the future, I'll make this emulator more user-friendly.`

https://github.com/AlexAltea/orbital/blob/master/README.md
