### ISSUE TITLE
Homebrew

### ISSUE THREAD

**Issue by niko1point0** [AlexAltea/orbital#64]
Hi, I have been developing some open-source homebrew tutorials, and I was wondering if you would like some samples to test with the emulator (triangle, cube, texture, etc). I assume that the emulator is not ready for homebrew yet, but when it is, would you like some samples? If so, which format would be easiest: iso, pkg, or just raw files ( elf executable, png textures, etc)?

**Comment by VelocityRa** [comment]
Not sure if Orbital has a need for this yet, but I'm part of another project that does. If you're interested message me on Discord (`velocity#4995`) or via email (it's on my GitHub profile).

**Comment by AlexAltea** [comment]
This is a low-level emulator, so such samples (userland applications) are mostly useless to us.
We don't have any, but check with @VelocityRa, he might be able to give you more information.
