### ISSUE TITLE
if orbital is QEMU based, then it might be possible to make Orbital available for high end android phones (or maybe ios)

### ISSUE THREAD

**Issue by IIWare** [AlexAltea/orbital#78]
Because of that, developers made unofficial QEMU support/app for iOS and Android, and if orbital is QEMU based, then QEMU support/app for iOS and android could be modified for QEMU support/app to run OrbisOS, and it can be available for android and iOS, if it's possible, there will be links for QEMU support/app for Android and iOS.

For iOS: The QEMU support source for iOS is https://github.com/utmapp/QEMU , you can fork it and modify it a little bit for OrbisOS and then you can create an iOS app with the modified QEMU support that emulates OrbisOS, or if preferred to fork an emulator app  that can run QEMU VMs, fork it from https://github.com/utmapp/UTM and you could modify it a little bit for OrbisOS to run in the app, and you can compile the modified source into an ipa app, of course, it requires jailbreak, once the ipa is compiled, the ipa can be converted in to deb using ipa2deb in terminal in jailbroken devices, and you can make a cydia repo for orbital, and you can add the deb in (https;//www,examplerepo,com/debs/**Orbital.deb**).

For android: The creator hasn't provided QEMU support yet, but you can fork the QEMU emulator app, the app is in https://github.com/limboemu/limbo , you could modify it a bit for OrbisOS to run in Limbo Emulator, then compile the modified source to an apk app.

this might be impossible to make, but this is just an idea for making Orbital available for mobile phones, like android and iOS, it could be available for phones in the future, depending on how hard it is to make Orbital for iOS and android.

**Comment by AlexAltea** [comment]
QEMU builds for any platform, but the HAXM accelerator that Orbital depends on is x86-only as it's basically a driver for hardware-assisted x86 virtualization present in Intel/AMD CPUs.

You *could* run QEMU/Orbital without accelerators in iOS/Android, but for it would be unbearably slow for PS4. So not practical at all. On top of that, the upcoming version of Orbital removes QEMU and offers no JIT based approach for non-x86 platforms, so this suggestion will become impossible in the future.

**Comment by marcussacana** [comment]
Yeah, maybe in 30 years who know

**Comment by Fox2Code** [comment]
Note: Some phone use the `x86_64` architecture and have compatible CPUs

But maintaining a Android build will be too troublesome because only a very few android phone use the `x86_64` architecture and instruction set needed to run the PS4 system, and for the size of the Orbital team it's not worth the effort.

Doing android build might also further confuse the community as these build would be only compatible on phone using the `x86_64` architecture, and most peoples have `arm` based phone.

So I agree with the idea of not supporting Android phones, even for the few having a compatible CPU.
