### ISSUE TITLE
orbital-grub not compiling on ArchLinux

### ISSUE THREAD

**Issue by ElCresh** [AlexAltea/orbital#8]
Hi,
I've tried to clone all repository related to orbital and tried compiling the solution but I'm stuck with orbital-grub compile.

These are the last lines of compile output:
> gcc -DHAVE_CONFIG_H -I. -I..  -Wall -W  -DGRUB_MACHINE_PCBIOS=1 -DGRUB_MACHINE=I386_PC -m32 -nostdinc -isystem /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include -I../include -I../include -DGRUB_FILE=\"video/i386/pc/vga.c\" -I. -I. -I.. -I.. -I../include -I../include -I../grub-core/lib/libgcrypt-grub/src/    -D_FILE_OFFSET_BITS=64 -Os -Wall -W -Wshadow -Wpointer-arith -Wundef -Wchar-subscripts -Wcomment -Wdeprecated-declarations -Wdisabled-optimization -Wdiv-by-zero -Wfloat-equal -Wformat-extra-args -Wformat-security -Wformat-y2k -Wimplicit -Wimplicit-function-declaration -Wimplicit-int -Wmain -Wmissing-braces -Wmissing-format-attribute -Wmultichar -Wparentheses -Wreturn-type -Wsequence-point -Wshadow -Wsign-compare -Wswitch -Wtrigraphs -Wunknown-pragmas -Wunused -Wunused-function -Wunused-label -Wunused-parameter -Wunused-value  -Wunused-variable -Wwrite-strings -Wnested-externs -Wstrict-prototypes -g -Wredundant-decls -Wmissing-prototypes -Wmissing-declarations  -Wextra -Wattributes -Wendif-labels -Winit-self -Wint-to-pointer-cast -Winvalid-pch -Wmissing-field-initializers -Wnonnull -Woverflow -Wvla -Wpointer-to-int-cast -Wstrict-aliasing -Wvariadic-macros -Wvolatile-register-var -Wpointer-sign -Wmissing-include-dirs -Wmissing-prototypes -Wmissing-declarations -Wformat=2 -march=i386 -m32 -mrtd -mregparm=3 -falign-jumps=1 -falign-loops=1 -falign-functions=1 -freg-struct-return -mno-mmx -mno-sse -mno-sse2 -mno-sse3 -mno-3dnow -msoft-float -fno-dwarf2-cfi-asm -mno-stack-arg-probe -fno-asynchronous-unwind-tables -fno-unwind-tables -Qn -fno-PIE -fno-pie -fno-stack-protector -Wtrampolines -Werror   -ffreestanding   -MT video/i386/pc/vga_module-vga.o -MD -MP -MF video/i386/pc/.deps-core/vga_module-vga.Tpo -c -o video/i386/pc/vga_module-vga.o `test -f 'video/i386/pc/vga.c' || echo './'`video/i386/pc/vga.c
mv -f term/.deps-core/serial_module-ns8250.Tpo term/.deps-core/serial_module-ns8250.Po
cc1: all warnings being treated as errors
make[3]: *** [Makefile:35745: normal_module-grub_script.yy.o] Error 1
make[3]: *** Waiting for unfinished jobs....
mv -f commands/i386/pc/.deps-core/sendkey_module-sendkey.Tpo commands/i386/pc/.deps-core/sendkey_module-sendkey.Po
mv -f term/.deps-core/serial_module-serial.Tpo term/.deps-core/serial_module-serial.Po
mv -f term/.deps-core/usb_keyboard_module-usb_keyboard.Tpo term/.deps-core/usb_keyboard_module-usb_keyboard.Po
mv -f video/i386/pc/.deps-core/vga_module-vga.Tpo video/i386/pc/.deps-core/vga_module-vga.Po
mv -f term/.deps-core/terminfo_module-tparm.Tpo term/.deps-core/terminfo_module-tparm.Po
mv -f term/.deps-core/terminfo_module-terminfo.Tpo term/.deps-core/terminfo_module-terminfo.Po
mv -f term/.deps-core/gfxterm_module-gfxterm.Tpo term/.deps-core/gfxterm_module-gfxterm.Po
make[3]: Leaving directory '/home/andrea/Desktop/ps4_emu/orbital-grub/grub-core'
make[2]: *** [Makefile:23530: all] Error 2
make[2]: Leaving directory '/home/andrea/Desktop/ps4_emu/orbital-grub/grub-core'
make[1]: *** [Makefile:10903: all-recursive] Error 1
make[1]: Leaving directory '/home/andrea/Desktop/ps4_emu/orbital-grub'
make: *** [Makefile:3129: all] Error 2

I've prepared makefile with:
>./autogen.sh
./configure --target=x86_64

**Comment by AlexAltea** [comment]
I don't see what's actually triggering the error. Are you able to compile the original GRUB repository (the one I forked `orbital-grub` from)? If you have still problems here, report it to the original developers.

**Comment by ElCresh** [comment]
Ok now I've tried original grub repository and installed xorriso that for some reason was missing on my pc. Now original grub and also your fork gave me te same error.

>grub_script.yy.c: In function ‘yy_fatal_error’:
grub_script.yy.c:18:22: error: statement with no effect [-Werror=unused-value]
                      ^
grub_script.yy.c:2366:2: note: in expansion of macro ‘fprintf’
  (void)yyg;
  ^~~~~~~
cc1: all warnings being treated as errors
make[3]: *** [Makefile:35745: normal_module-grub_script.yy.o] Error 1
make[3]: Leaving directory '/home/andrea/Desktop/emulators/ps4_emu/orbital-grub/grub-core'
make[2]: *** [Makefile:23530: all] Error 2
make[2]: Leaving directory '/home/andrea/Desktop/emulators/ps4_emu/orbital-grub/grub-core'
make[1]: *** [Makefile:10903: all-recursive] Error 1
make[1]: Leaving directory '/home/andrea/Desktop/emulators/ps4_emu/orbital-grub'
make: *** [Makefile:3129: all] Error 2

I suppose that is more approriate if i'll report this issue to grub dev repo.

**Comment by ElCresh** [comment]
I've found their bug tracker (they have some broken link on their website) and this is the report: http://savannah.gnu.org/bugs/?53471
