### ISSUE TITLE
can it run ps2 emulated game of the PS Store ?

### ISSUE THREAD

**Issue by seb16120** [AlexAltea/orbital#81]
like this one (Rogue Galaxy) : https://store.playstation.com/fr-fr/product/EP9000-CUSA02271_00-SCES545520000001/

**Comment by Masamune3210** [comment]
Lets work on running native games first lol

**Comment by marcussacana** [comment]
PCSX2: I'm a joke for you?

**Comment by seb16120** [comment]
I know pcsx2 ... Just want know if it's harder or easier to run this type
of game on the PS4 emulator.

Maybe it's easier but the PS4 emulator can't access the PS Store so can't
have access anything of the store.

Le mar. 17 août 2021 à 03:12, Marcus André ***@***.***> a
écrit :

**Comment by Matriks404** [comment]
Wouldn't running an emulator on a emulated platform be one of the most difficult tasks for emulator to handle? I think we'll eventually get there, but for now it's a dream.

**Comment by VHSCODE** [comment]
This would be a cool milestone , that would implty that the emulator is a very mature state, but for now, the focus is to run native games, but it's a cool idea nonetheless

**Comment by AlexAltea** [comment]
Not right now.
