### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by Light-YT** [AlexAltea/orbital#82]
> $ cmake ..

> -- The CXX compiler identification is GNU 9.3.0
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> CMake Error at CMakeLists.txt:20 (find_package):
>   By not providing "FindSDL2.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "SDL2", but
>   CMake did not find one.

 >  Could not find a package configuration file provided by "SDL2" with any of
 >  the following names:

  >   SDL2Config.cmake
  >   sdl2-config.cmake

  > Add the installation prefix of "SDL2" to CMAKE_PREFIX_PATH or set
  > "SDL2_DIR" to a directory containing one of the above files.  If "SDL2"
  > provides a separate development package or SDK, be sure it has been
  > installed.

> -- Configuring incomplete, errors occurred!

> See also "/home/light/Desktop/orbital/build/CMakeFiles/CMakeOutput.log".

**Comment by mark2185** [comment]
Do you have SDL2 installed?

**Comment by Light-YT** [comment]
> Do you have SDL2 installed?

yes but it also gives me the same error with imgui

**Comment by TylerJaacks** [comment]
I'm also facing this issue I ran this following command before the cmake build command. vcpkg install glslang imgui libzip sdl2[vulkan] vulkan zlib

**Comment by TylerJaacks** [comment]
@Light-YT I did this is and it resolved the errors but I still get the error saying that we need to wait for the core.cmake.

```
list(APPEND CMAKE_PREFIX_PATH E:\\vcpkg\\packages\\sdl2_x86-windows)
list(APPEND CMAKE_PREFIX_PATH E:\\vcpkg\\packages\\imgui_x86-windows)
list(APPEND CMAKE_PREFIX_PATH E:\\vcpkg\\packages\\fmt_x86-windows)
list(APPEND CMAKE_PREFIX_PATH E:\\vcpkg\\packages\\rapidjson_x86-windows)
list(APPEND CMAKE_PREFIX_PATH E:\\vcpkg\\packages\\zlib_x86-windows)
```

**Comment by AlexAltea** [comment]
That's now how *vcpkg* is supposed to work, but anyway, I'm closing this issue since this is unrelated to Orbital.

**Comment by n0bodyImp0rtant** [comment]
Hey, I have no idea who y'all are, y'all aren't emailing the right person

**Comment by telans** [comment]
>  You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub:

You must've subscribed at some point.

**Comment by AlexAltea** [comment]
@n0bodyImp0rtant You are watching the repository, see: https://github.com/AlexAltea/orbital/watchers?page=8

As a result, you are getting notifications for all ongoing discussions. If you don't care, then just unwatch it.
