### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by koniecznymikolaj** [AlexAltea/orbital#84]
`sudo cmake -B build .
CMake Error at CMakeLists.txt:21 (find_package):
  By not providing "Findimgui.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "imgui", but
  CMake did not find one.

  Could not find a package configuration file provided by "imgui" with any of
  the following names:

    imguiConfig.cmake
    imgui-config.cmake

  Add the installation prefix of "imgui" to CMAKE_PREFIX_PATH or set
  "imgui_DIR" to a directory containing one of the above files.  If "imgui"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!`

**Comment by mark2185** [comment]
https://github.com/AlexAltea/orbital/issues/83
